# Site settings
title: Hello World!
email: your-email@domain.com
description: "Founders and coders!"
baseurl: "/playground"
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
